"""
report_generator.py
--------------------
Builds a downloadable PDF summary report for a dataset:
overview, missing values and column profile.
"""

import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def generate_pdf_report(dataset_name, overview, column_profiles, generated_by="IDAA"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=1.5 * cm, bottomMargin=1.5 * cm,
                             leftMargin=1.5 * cm, rightMargin=1.5 * cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"],
                                  textColor=colors.HexColor("#4c2fbf"), fontSize=22)
    heading_style = ParagraphStyle("HeadingStyle", parent=styles["Heading2"],
                                    textColor=colors.HexColor("#7c5cff"), spaceBefore=14, spaceAfter=8)
    normal_style = styles["Normal"]

    elements = []
    elements.append(Paragraph("Intelligent Data Analysis Assistant", title_style))
    elements.append(Paragraph("Automated Data Report", styles["Heading3"]))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(f"<b>Dataset:</b> {dataset_name}", normal_style))
    elements.append(Spacer(1, 14))

    # Overview section
    elements.append(Paragraph("1. Dataset Overview", heading_style))
    overview_data = [
        ["Rows", str(overview["n_rows"])],
        ["Columns", str(overview["n_cols"])],
        ["Numeric Columns", str(len(overview["numeric_cols"]))],
        ["Categorical Columns", str(len(overview["categorical_cols"]))],
        ["Total Missing Values", str(overview["total_missing"])],
        ["Duplicate Rows", str(overview["duplicate_rows"])],
        ["Memory Usage", f"{overview['memory_kb']} KB"],
    ]
    t = Table(overview_data, colWidths=[7 * cm, 8 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#efe9ff")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#1f1235")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d3c9f7")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)

    # Column Profile
    elements.append(Paragraph("2. Column Profile", heading_style))
    col_data = [["Column", "Type", "Missing %", "Unique Values"]]
    for c in column_profiles:
        col_data.append([c["name"], c["dtype"], f"{c['missing_pct']}%", str(c["unique"])])
    t3 = Table(col_data, colWidths=[6 * cm, 3.5 * cm, 3 * cm, 3 * cm], repeatRows=1)
    t3.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#22d3ee")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d3c9f7")),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f3ff")]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t3)

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        f"<i>Report generated by {generated_by} — Intelligent Data Analysis Assistant.</i>",
        ParagraphStyle("footer", parent=normal_style, fontSize=8, textColor=colors.grey)
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
